export enum NotificationType {
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  TRANSACTION_WAITING_FOR_SIGNATURES = 'TRANSACTION_WAITING_FOR_SIGNATURES',
  TRANSACTION_WAITING_FOR_SIGNATURES_REMINDER = 'TRANSACTION_WAITING_FOR_SIGNATURES_REMINDER',
  TRANSACTION_WAITING_FOR_SIGNATURES_REMINDER_MANUAL = 'TRANSACTION_WAITING_FOR_SIGNATURES_REMINDER_MANUAL',
  TRANSACTION_READY_FOR_EXECUTION = 'TRANSACTION_READY_FOR_EXECUTION',
  TRANSACTION_EXECUTED = 'TRANSACTION_EXECUTED',
  TRANSACTION_EXPIRED = 'TRANSACTION_EXPIRED',
  TRANSACTION_CANCELLED = 'TRANSACTION_CANCELLED',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  TRANSACTION_REJECTED = 'TRANSACTION_REJECTED',
  TRANSACTION_INDICATOR_APPROVE = 'TRANSACTION_INDICATOR_APPROVE',
  TRANSACTION_APPROVED = 'TRANSACTION_APPROVED',
  TRANSACTION_APPROVAL_REJECTION = 'TRANSACTION_APPROVAL_REJECTION',
  TRANSACTION_INDICATOR_REJECTED = 'TRANSACTION_INDICATOR_REJECTED',
  TRANSACTION_INDICATOR_SIGN = 'TRANSACTION_INDICATOR_SIGN',
  TRANSACTION_INDICATOR_EXECUTABLE = 'TRANSACTION_INDICATOR_EXECUTABLE',
  TRANSACTION_INDICATOR_EXECUTED = 'TRANSACTION_INDICATOR_EXECUTED',
  TRANSACTION_INDICATOR_FAILED = 'TRANSACTION_INDICATOR_FAILED',
  TRANSACTION_INDICATOR_CANCELLED = 'TRANSACTION_INDICATOR_CANCELLED',
  TRANSACTION_INDICATOR_EXPIRED = 'TRANSACTION_INDICATOR_EXPIRED',
  TRANSACTION_INDICATOR_ARCHIVED = 'TRANSACTION_INDICATOR_ARCHIVED',
  USER_REGISTERED = 'USER_REGISTERED',
}

export interface INotificationReceiverCore {
  id: number;
  notificationId: number;
  isRead: boolean;
}

export interface INotificationReceiver extends INotificationReceiverCore {
  notification: INotification;
}

export interface NotificationAdditionalData {
  network: string;
  groupId?: number;
}

export interface INotification {
  id: number;
  type: NotificationType;
  entityId?: number;
  actorId?: number;
  additionalData: NotificationAdditionalData;
  isEmailSent?: boolean;
  createdAt: Date;
}

export interface IUpdateNotificationReceiver {
  id: number;
  isRead: boolean;
}
