import { MAX_USER_KEYS } from '.';

export enum ErrorCodes {
  NPMOP = 'NPMOP',
  INOP = 'INOP',
  UNKWN = 'UNKWN',
  SNMP = 'SNMP',
  TE = 'TE',
  TEX = 'TEX',
  FST = 'FST',
  OTIP = 'OTIP',
  OMTIP = 'OMTIP',
  TNF = 'TNF',
  TAP = 'TAP',
  TAX = 'TAX',
  TNRS = 'TNRS',
  TNRA = 'TNRA',
  TA = 'TA',
  SAD = 'SAD',
  KNRS = 'KNRS',
  PU = 'PU',
  PNY = 'PNY',
  CRYFO = 'CRYFO',
  UNF = 'UNF',
  IFP = 'IFP',
  IPK = 'IPK',
  ISP = 'ISP',
  IRP = 'IRP',
  IPP = 'IPP',
  INP = 'INP',
  ISNMP = 'ISNMP',
  ANF = 'ANF',
  RANF = 'RANF',
  ONF = 'ONF',
  UMK = 'UMK',
  ISNMPN = 'ISNMPN',
  KNF = 'KNF',
  NNF = 'NNF',
  IB = 'IB',
  TOS = 'TOS',
  IO = 'IO',
  TNVN = 'TNVN',
  FSTC = 'FSTC',
  FSUK = 'FSUK',
  FSTG = 'FSTG',
}

export const ErrorMessages: { [key in ErrorCodes]: string } = {
  [ErrorCodes.NPMOP]: 'New password should not be the old password',
  [ErrorCodes.INOP]: 'Invalid old password',
  [ErrorCodes.UNKWN]: 'Unknown error',
  [ErrorCodes.SNMP]: 'The signature does not match the public key',
  [ErrorCodes.TE]: 'Transaction is expired',
  [ErrorCodes.TEX]: 'Transaction already exists',
  [ErrorCodes.FST]: 'Failed to save transaction',
  [ErrorCodes.OTIP]: 'Only transactions in progress can be canceled',
  [ErrorCodes.OMTIP]: 'Only manual transaction in progress can be archived',
  [ErrorCodes.TNF]: 'Transaction not found',
  [ErrorCodes.TAP]: 'Transaction already approved',
  [ErrorCodes.TAX]: 'Transaction already executed',
  [ErrorCodes.TNRS]: 'Transaction not awaiting signatures',
  [ErrorCodes.TNRA]: 'Transaction not awaiting approval',
  [ErrorCodes.TA]: 'Transaction archived',
  [ErrorCodes.SAD]: 'Signature already added',
  [ErrorCodes.KNRS]: 'Key not required to sign',
  [ErrorCodes.PU]: 'Public key already used',
  [ErrorCodes.PNY]: 'Provided key/s not yours',
  [ErrorCodes.CRYFO]: 'Cannot remove yourself from the organization',
  [ErrorCodes.UNF]: 'User not found',
  [ErrorCodes.IFP]: 'Invalid filter parameters',
  [ErrorCodes.IPK]: 'Invalid public key',
  [ErrorCodes.ISP]: 'Invalid sorting parameters',
  [ErrorCodes.IRP]: 'Invalid Request parameters',
  [ErrorCodes.IPP]:
    'Invalid pagination parameters. Page and size should be positive integers and size should be less than 100',
  [ErrorCodes.INP]: 'Invalid network parameter',
  [ErrorCodes.ISNMP]: 'Invalid signature map',
  [ErrorCodes.ANF]: 'Approver not found',
  [ErrorCodes.RANF]: 'Root approver not found',
  [ErrorCodes.ONF]: 'Observer not found',
  [ErrorCodes.UMK]: `User must have up to ${MAX_USER_KEYS} keys`,
  [ErrorCodes.ISNMPN]: 'Invalid signature map node parameters',
  [ErrorCodes.KNF]: 'Key not found',
  [ErrorCodes.NNF]: 'Notification not found',
  [ErrorCodes.IB]: 'Invalid body',
  [ErrorCodes.TOS]: 'Transaction is over the size limit and cannot be executed',
  [ErrorCodes.IO]: 'Invalid operation',
  [ErrorCodes.TNVN]: 'Transaction is not valid on the configured network (contains node account IDs that are not present on the network)',
  [ErrorCodes.FSTC]: 'Failed to save transaction comment',
  [ErrorCodes.FSUK]: 'Failed to save user key',
  [ErrorCodes.FSTG]: 'Failed to save transaction group',
};
